POST localhost:8015/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "newUs",
  "password": "admin123"
}

###

POST localhost:8018/api/users/login HTTP/1.1
Content-Type: application/json

{
  "username": "newUs",
  "password": "admin123"
}

###

GET http://localhost:8010/api/users/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8010/api/users/ping HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8010/api/messages/ping HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8018/api/messages HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8018/api/messages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuZXdVcyIsImV4cCI6MTc1MTM5MDUwOX0.8HyqzOLsy6QY7opEB0ii-s5J-w61oUeoycVK5oXZSZA

{
  "content": "new comment"
}