POST localhost:8040/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "newUs1",
  "password": "admin123"
}

###

POST localhost:8025/api/users/login HTTP/1.1
Content-Type: application/json

{
  "username": "newUs1",
  "password": "admin123"
}

###

GET http://localhost:8040/api/users/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8010/api/users/ping HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8010/api/messages/ping HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8018/api/messages HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8025/api/messages/ HTTP/1.1
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuZXdVczEiLCJleHAiOjE3NTE0MDE5NjV9.7xKBJ47VyYwiR2LBdXYLuAPYMySlrprv_vPsiPbh5z8

{
  "content": "new comddment"
}

###

POST http://localhost:8040/api/messages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuZXdVczEiLCJleHAiOjE3NTE0MDEwNzd9.pxol62H6Lsif--DufY6UcMG1ds3EY0FwTZPVC1hTfp4

{
  "content": "new comddment"
}