POST localhost:8040/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "newUs1",
  "password": "admin123"
}

###

POST localhost:8040/api/users/login HTTP/1.1
Content-Type: application/json

{
  "username": "newUs1",
  "password": "admin123"
}

###

GET http://localhost:8040/api/users/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8010/api/users/ping HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8010/api/messages/ping HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8018/api/messages HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8018/api/messages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuZXdVczEiLCJleHAiOjE3NTEzOTc5MDZ9.7s2FVB8ap0mmh8rO8v57D6GmQKu_OM4tM-avXOLxRxM

{
  "content": "new comddment"
}